Repository acstech/doppler-api, pull requests merged in 2018-07, with the labels that each got.

#45 fixed excessive cpu usage
  internal/liveupdate/liveupdate.go
Labels: MVP, bug, real time processing

#47 fixed mutex error
  internal/liveupdate/liveupdate.go
Labels: MVP, bug, enhancement

#48 Matts/update data send
  internal/liveupdate/liveupdate.go
Labels: MVP

#51 Docker deployement
  .dockerignore
  .env.Default
  Dockerfile
  Gopkg.lock
  README.md
  cmd/doppler-api/config.go
  cmd/doppler-api/main.go
  entrypoint.sh
  internal/influx/influxclient.go
  internal/liveupdate/liveupdate.go
  vendor/github.com/joho/godotenv/autoload/autoload.go
Labels: MVP, enhancement

#52 Peterk/dockerfile
  Dockerfile
  entrypoint.sh
Labels: MVP, enhancement

#55 Matts/re
  cmd/doppler-api/main.go
  internal/liveupdate/liveupdate.go
  internal/service/consumer.go
  internal/service/websockets.go
Labels: MVP, enhancement

#56 created struct for errors that are sent over websocket
  internal/service/websockets.go
Labels: MVP

#63 Matts/ajax
  cmd/doppler-api/main.go
  internal/influx/influxclient.go
  internal/service/influxDB.go
Labels: Exceeds, frontend queries

#65 Matts/response
  internal/service/influxDB.go
Labels: Exceeds, enhancement

#66 created context to handle interrupts, added server shutdown deadline
  cmd/doppler-api/main.go
  internal/service/consumer.go
Labels: Exceeds, enhancement

#67 Matts/linter
  README.md
  cmd/doppler-api/main.go
  internal/couchbase/couchbaseconfig.go
  internal/influx/influxclient.go
  internal/service/consumer.go
  internal/service/influxDB.go
  internal/service/websockets.go
Labels: Exceeds

#68 couchbase linter error checks
  internal/couchbase/couchbaseconfig.go
Labels: Exceeds

#71 bind influx query parameters && take seconds from frontend
  internal/service/influxDB.go
Labels: Exceeds, enhancement

#74 changed divide by 1000000000 to multiply
  internal/service/influxDB.go
Labels: Exceeds

#75 removed bucketing limit
  internal/service/influxDB.go
  internal/service/websockets.go
Labels: Exceeds
