Repository acstech/doppler-api, pull requests merged in 2018-06, with the labels that each got.

#11 couchbase working
  internal/couchbase/couchbaseconfig.go
  internal/main/consumer.go
  internal/main/main.go
Labels: enhancement

#16 Added config setup for Couchbase
  .env.default
  Gopkg.lock
  README.md
  internal/main/main.go
  vendor/github.com/joho/godotenv/.gitignore
  vendor/github.com/joho/godotenv/.travis.yml
  vendor/github.com/joho/godotenv/LICENCE
  vendor/github.com/joho/godotenv/README.md
  vendor/github.com/joho/godotenv/godotenv.go
Labels: enhancement

#21 Ben/flow
  README.md
  internal/couchbase/couchbaseconfig.go
Labels: enhancement

#22 updated the README
  README.md
Labels: enhancement

#25 file cleanup
  .env.Default
  README.md
  cmd/doppler-api/main.go
  internal/main/consumer.go
  internal/main/main.go
Labels: enhancement

#27 websocket message reading basics
  cmd/doppler-api/main.go
  internal/liveupdate/liveupdate.go
Labels: enhancement, real time processing

#28 Matts/one client testing
  cmd/doppler-api/main.go
  internal/liveupdate/liveupdate.go
Labels: enhancement

#31 Matts/batching
  internal/liveupdate/liveupdate.go
Labels: enhancement, real time processing

#36 Peterk/error update
  cmd/doppler-api/main.go
  internal/couchbase/couchbaseconfig.go
  internal/liveupdate/liveupdate.go
Labels: MVP, enhancement

#37 fixed clientID sign in bug
  internal/liveupdate/liveupdate.go
Labels: MVP, bug, enhancement

#40 Update how event list is retrieved from Couchbase
  internal/couchbase/couchbaseconfig.go
  internal/liveupdate/liveupdate.go
Labels: MVP, bug, enhancement
